// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/casaevideo.ts";
import * as $$$$$$$$$$$1 from "./apps/deco/analytics.ts";
import * as $$$$$$$$$$$2 from "./apps/deco/htmx.ts";
import * as $$$$$$$$$$$3 from "./apps/deco/shopify.ts";
import * as $$$$$$$$$$$4 from "./apps/site.ts";
import * as $$$$$$$$$$$5 from "./apps/vtex.ts";
import * as $$$$$$0 from "./sections/NovaSecao.tsx";
import * as $$$$$$1 from "./sections/Theme/Theme.tsx";

const manifest = {
  "sections": {
    "site/sections/NovaSecao.tsx": $$$$$$0,
    "site/sections/Theme/Theme.tsx": $$$$$$1,
  },
  "apps": {
    "site/apps/casaevideo.ts": $$$$$$$$$$$0,
    "site/apps/deco/analytics.ts": $$$$$$$$$$$1,
    "site/apps/deco/htmx.ts": $$$$$$$$$$$2,
    "site/apps/deco/shopify.ts": $$$$$$$$$$$3,
    "site/apps/site.ts": $$$$$$$$$$$4,
    "site/apps/vtex.ts": $$$$$$$$$$$5,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
